### ISSUE TITLE
[Crash] random unknown crash.

### ISSUE THREAD

**Issue by SylisMC** [tyap-lyap/artifality#6] opened 2021-08-25 20:07 UTC
I kept getting this crash with my modlist issue went away when remiving the mod, im not sure whats causing the conflict but i figured id leave the report here. all the information you need should be in there

mc 1.17.1

https://bytebin.lucko.me/QKZhNpJwY8

**Comment by PinkGoosik** [comment] 2021-08-26 07:17
Just found out that this crash caused by incompatibility with pehkui mod

**Comment by SylisMC** [comment] 2021-08-26 14:45
ahh, well that's at least good to know, I had to mess with it for about an hour trying to figure it out, but it can sometimes take a while for the crash to happen, so i ended up getting frustrated and quit trying to narrow down the mods list haha sorry about that

**Comment by PinkGoosik** [comment] 2021-08-26 15:29
yeah that's pretty weird crash i can't really figure out how to fix it

**Comment by MoriyaShiine** [comment] 2021-08-29 02:34
Oh I just got an issue report mentioning this lol (https://github.com/MoriyaShiine/bewitchment/issues/193), I can PR a fix tomorrow

**Comment by Virtuoel** [comment] 2021-08-29 03:19
This has (potentially) been resolved on Pehkui's end and a (hopefully) fixed version will be released in a few days.

**Comment by PinkGoosik** [comment] 2021-09-01 16:38
fixed in 0.3.4

**Closed as completed by PinkGoosik** 2021-09-01 16:38 UTC
Labels: incompatibility, crash
